import type { HealthRecordsSummary } from './api';

/** Client fallback when workspace payload omits healthRecords.portals */
export const EMPTY_HEALTH_RECORDS_FALLBACK = (): HealthRecordsSummary => ({
  connectedCount: 0,
  totalRecords: 0,
  lastSyncAt: null,
  nextAutoSyncAt: null,
  autoSyncEnabled: true,
  syncHealth: 'none',
  liveMode: false,
  portals: [
    {
      id: 'epic_mychart',
      name: 'Epic MyChart',
      vendor: 'Epic Systems',
      authMode: 'oauth_smart',
      fhirVersion: 'R4',
      accent: 'teal',
      recordTypes: ['labs', 'medications', 'visits', 'allergies', 'conditions', 'immunizations'],
      connection: {
        portalId: 'epic_mychart',
        status: 'disconnected',
        connectedAt: null,
        lastSyncAt: null,
        nextSyncDueAt: null,
        recordCount: 0,
        syncStatus: 'idle',
        message: '',
        records: [],
      },
    },
    {
      id: 'cerner',
      name: 'Cerner / Oracle Health',
      vendor: 'Oracle Health',
      authMode: 'oauth_smart',
      fhirVersion: 'R4',
      accent: 'blue',
      recordTypes: ['labs', 'medications', 'visits', 'vitals', 'procedures'],
      connection: { portalId: 'cerner', status: 'disconnected', connectedAt: null, lastSyncAt: null, nextSyncDueAt: null, recordCount: 0, syncStatus: 'idle', message: '', records: [] },
    },
    {
      id: 'apple_health',
      name: 'Apple Health',
      vendor: 'Apple',
      authMode: 'device_export',
      fhirVersion: 'export',
      accent: 'rose',
      recordTypes: ['vitals', 'activity', 'labs', 'medications'],
      connection: { portalId: 'apple_health', status: 'disconnected', connectedAt: null, lastSyncAt: null, nextSyncDueAt: null, recordCount: 0, syncStatus: 'idle', message: '', records: [] },
    },
    {
      id: 'google_health',
      name: 'Google Health Connect',
      vendor: 'Google',
      authMode: 'device_export',
      fhirVersion: 'export',
      accent: 'green',
      recordTypes: ['vitals', 'activity', 'nutrition', 'sleep'],
      connection: { portalId: 'google_health', status: 'disconnected', connectedAt: null, lastSyncAt: null, nextSyncDueAt: null, recordCount: 0, syncStatus: 'idle', message: '', records: [] },
    },
  ],
  unifiedTimeline: [],
  byType: {},
});
