import type { Language, UserRole } from '../types';

export interface AccessCopy {
  eyebrow: string;
  title: string;
  subtitle: string;
  primary: string;
  back: string;
  switchLabel: string;
  switchAction: string;
  working: string;
  fields: {
    fullName: string;
    role: string;
    organization: string;
    email: string;
    password: string;
  };
  placeholders: {
    fullName: string;
    organization: string;
    email: string;
    password: string;
  };
  roles: Partial<Record<UserRole, string>>;
  errors: {
    missingName: string;
    missingCredentials: string;
    incorrectCredentials: string;
    duplicateEmail: string;
    requestFailed: string;
  };
}

export type AccessMode = 'signin' | 'signup';

export const COPY: Record<Language, Record<AccessMode, AccessCopy>> = {
  en: {
    signin: {
      eyebrow: 'Welcome back',
      title: 'Good to see you again',
      subtitle: 'Open your family daily view.',
      primary: 'Sign in',
      back: 'Back To Public Site',
      switchLabel: 'Need a new account?',
      switchAction: 'Create account',
      working: 'Working...',
      fields: {
        fullName: 'Full Name',
        role: 'Role',
        organization: 'Clinic / Organization',
        email: 'Email',
        password: 'Password',
      },
      placeholders: {
        fullName: 'Taylor Morgan',
        organization: 'Optional',
        email: 'you@example.com',
        password: 'Enter your password',
      },
      roles: {
        parent: 'Parent',
        adult: 'Adult Living With Diabetes',
        caregiver: 'Support Adult',
      },
      errors: {
        missingName: 'Add your name.',
        missingCredentials: 'Email and password are required.',
        incorrectCredentials: 'Email or password is incorrect.',
        duplicateEmail: 'This email already has a Type1 and 2 account.',
        requestFailed: 'Request failed. Please try again.',
      },
    },
    signup: {
      eyebrow: 'Join Type1 and 2',
      title: 'Create your family space',
      subtitle: 'For type 1 or type 2 — parents, adults, and support adults.',
      primary: 'Create Account',
      back: 'Back To Public Site',
      switchLabel: 'Already created one?',
      switchAction: 'Sign in',
      working: 'Working...',
      fields: {
        fullName: 'Full Name',
        role: 'Role',
        organization: 'Clinic / Organization',
        email: 'Email',
        password: 'Password',
      },
      placeholders: {
        fullName: 'Taylor Morgan',
        organization: 'Optional',
        email: 'you@example.com',
        password: 'Choose a password',
      },
      roles: {
        parent: 'Parent',
        adult: 'Adult Living With Diabetes',
        caregiver: 'Support Adult',
      },
      errors: {
        missingName: 'Add your name.',
        missingCredentials: 'Email and password are required.',
        incorrectCredentials: 'Email or password is incorrect.',
        duplicateEmail: 'This email already has a Type1 and 2 account.',
        requestFailed: 'Request failed. Please try again.',
      },
    },
  },
  ru: {
    signin: {
      eyebrow: 'С возвращением',
      title: 'Рады снова видеть вас',
      subtitle: 'Откройте семейную картину дня.',
      primary: 'Войти',
      back: 'Назад На Публичный Сайт',
      switchLabel: 'Нужен новый аккаунт?',
      switchAction: 'Создать аккаунт',
      working: 'Выполняется...',
      fields: {
        fullName: 'Полное Имя',
        role: 'Роль',
        organization: 'Клиника / Организация',
        email: 'Email',
        password: 'Пароль',
      },
      placeholders: {
        fullName: 'Анна Иванова',
        organization: 'Необязательно',
        email: 'you@example.com',
        password: 'Введите пароль',
      },
      roles: {
        parent: 'Родитель',
        adult: 'Взрослый С Диабетом',
        caregiver: 'Помогающий Взрослый',
      },
      errors: {
        missingName: 'Добавьте имя, чтобы пространство ощущалось персональным.',
        missingCredentials: 'Нужны email и пароль.',
        incorrectCredentials: 'Неверный email или пароль.',
        duplicateEmail: 'Для этого email уже существует аккаунт Type1 and 2.',
        requestFailed: 'Запрос не выполнен. Попробуйте ещё раз.',
      },
    },
    signup: {
      eyebrow: 'Присоединиться',
      title: 'Создайте семейное пространство',
      subtitle: 'Для типа 1 или 2 — дети, родители и близкие взрослые.',
      primary: 'Создать Аккаунт',
      back: 'Назад На Публичный Сайт',
      switchLabel: 'Аккаунт уже создан?',
      switchAction: 'Войти',
      working: 'Выполняется...',
      fields: {
        fullName: 'Полное Имя',
        role: 'Роль',
        organization: 'Клиника / Организация',
        email: 'Email',
        password: 'Пароль',
      },
      placeholders: {
        fullName: 'Анна Иванова',
        organization: 'Необязательно',
        email: 'you@example.com',
        password: 'Придумайте пароль',
      },
      roles: {
        parent: 'Родитель',
        adult: 'Взрослый С Диабетом',
        caregiver: 'Помогающий Взрослый',
      },
      errors: {
        missingName: 'Добавьте имя, чтобы пространство ощущалось персональным.',
        missingCredentials: 'Нужны email и пароль.',
        incorrectCredentials: 'Неверный email или пароль.',
        duplicateEmail: 'Для этого email уже существует аккаунт Type1 and 2.',
        requestFailed: 'Запрос не выполнен. Попробуйте ещё раз.',
      },
    },
  },
  uk: {
    signin: {
      eyebrow: 'Доступ Для Учасників',
      title: 'Відкрийте вашу картину дня',
      subtitle: 'Увійдіть, щоб відкрити щоденний огляд підтримки.',
      primary: 'Відкрити Картину Дня',
      back: 'Назад На Публічний Сайт',
      switchLabel: 'Потрібен новий акаунт?',
      switchAction: 'Створити акаунт',
      working: 'Виконується...',
      fields: {
        fullName: 'Повне Імʼя',
        role: 'Роль',
        organization: 'Клініка / Організація',
        email: 'Email',
        password: 'Пароль',
      },
      placeholders: {
        fullName: 'Анна Іванова',
        organization: 'Необовʼязково',
        email: 'you@example.com',
        password: 'Введіть пароль',
      },
      roles: {
        parent: 'Батько Або Мати',
        adult: 'Дорослий З Діабетом',
        caregiver: 'Дорослий Для Підтримки',
      },
      errors: {
        missingName: 'Додайте імʼя, щоб простір відчувався персональним.',
        missingCredentials: 'Потрібні email і пароль.',
        incorrectCredentials: 'Неправильний email або пароль.',
        duplicateEmail: 'Для цього email уже існує акаунт Type1 and 2.',
        requestFailed: 'Запит не виконано. Спробуйте ще раз.',
      },
    },
    signup: {
      eyebrow: 'Створення Акаунта',
      title: 'Створіть окремий Type1 and 2-акаунт',
      subtitle: 'Створіть акаунт Type1 and 2 для щоденної підтримки родини.',
      primary: 'Створити Акаунт',
      back: 'Назад На Публічний Сайт',
      switchLabel: 'Акаунт уже створено?',
      switchAction: 'Увійти',
      working: 'Виконується...',
      fields: {
        fullName: 'Повне Імʼя',
        role: 'Роль',
        organization: 'Клініка / Організація',
        email: 'Email',
        password: 'Пароль',
      },
      placeholders: {
        fullName: 'Анна Іванова',
        organization: 'Необовʼязково',
        email: 'you@example.com',
        password: 'Придумайте пароль',
      },
      roles: {
        parent: 'Батько Або Мати',
        adult: 'Дорослий З Діабетом',
        caregiver: 'Дорослий Для Підтримки',
      },
      errors: {
        missingName: 'Додайте імʼя, щоб простір відчувався персональним.',
        missingCredentials: 'Потрібні email і пароль.',
        incorrectCredentials: 'Неправильний email або пароль.',
        duplicateEmail: 'Для цього email уже існує акаунт Type1 and 2.',
        requestFailed: 'Запит не виконано. Спробуйте ще раз.',
      },
    },
  },
  es: {
    signin: {
      eyebrow: 'Acceso De Miembros',
      title: 'Abre tu espacio de apoyo Type1 and 2',
      subtitle: 'Usa tu cuenta de Type1 and 2 para entrar en tu área de apoyo.',
      primary: 'Abrir Espacio',
      back: 'Volver Al Sitio Público',
      switchLabel: '¿Necesitas una cuenta nueva?',
      switchAction: 'Crear cuenta',
      working: 'Procesando...',
      fields: {
        fullName: 'Nombre Completo',
        role: 'Rol',
        organization: 'Clínica / Organización',
        email: 'Email',
        password: 'Contraseña',
      },
      placeholders: {
        fullName: 'Ana García',
        organization: 'Opcional',
        email: 'you@example.com',
        password: 'Introduce tu contraseña',
      },
      roles: {
        parent: 'Padre O Madre',
        adult: 'Adulto Con Diabetes',
        caregiver: 'Adulto De Apoyo',
      },
      errors: {
        missingName: 'Añade un nombre para que el espacio se sienta personal.',
        missingCredentials: 'El email y la contraseña son obligatorios.',
        incorrectCredentials: 'El email o la contraseña son incorrectos.',
        duplicateEmail: 'Este email ya tiene una cuenta de Type1 and 2.',
        requestFailed: 'La solicitud falló. Inténtalo de nuevo.',
      },
    },
    signup: {
      eyebrow: 'Crear Cuenta',
      title: 'Crea tu cuenta Type1 and 2',
      subtitle: 'Crea tu cuenta Type1 and 2 para el apoyo familiar diario.',
      primary: 'Crear Espacio',
      back: 'Volver Al Sitio Público',
      switchLabel: '¿Ya tienes una cuenta?',
      switchAction: 'Iniciar sesión',
      working: 'Procesando...',
      fields: {
        fullName: 'Nombre Completo',
        role: 'Rol',
        organization: 'Clínica / Organización',
        email: 'Email',
        password: 'Contraseña',
      },
      placeholders: {
        fullName: 'Ana García',
        organization: 'Opcional',
        email: 'you@example.com',
        password: 'Elige una contraseña',
      },
      roles: {
        parent: 'Padre O Madre',
        adult: 'Adulto Con Diabetes',
        caregiver: 'Adulto De Apoyo',
      },
      errors: {
        missingName: 'Añade un nombre para que el espacio se sienta personal.',
        missingCredentials: 'El email y la contraseña son obligatorios.',
        incorrectCredentials: 'El email o la contraseña son incorrectos.',
        duplicateEmail: 'Este email ya tiene una cuenta de Type1 and 2.',
        requestFailed: 'La solicitud falló. Inténtalo de nuevo.',
      },
    },
  },
  fr: {
    signin: {
      eyebrow: 'Accès Membre',
      title: 'Ouvrez votre espace Type1 and 2',
      subtitle: 'Utilisez votre compte Type1 and 2 pour accéder à votre espace de soutien.',
      primary: 'Ouvrir L’Espace',
      back: 'Retour Au Site Public',
      switchLabel: 'Besoin d’un nouveau compte ?',
      switchAction: 'Créer un compte',
      working: 'Traitement...',
      fields: {
        fullName: 'Nom Complet',
        role: 'Rôle',
        organization: 'Clinique / Organisation',
        email: 'Email',
        password: 'Mot De Passe',
      },
      placeholders: {
        fullName: 'Anne Martin',
        organization: 'Optionnel',
        email: 'you@example.com',
        password: 'Entrez votre mot de passe',
      },
      roles: {
        parent: 'Parent',
        adult: 'Adulte Vivant Avec Un Diabète',
        caregiver: 'Adulte De Soutien',
      },
      errors: {
        missingName: 'Ajoutez un nom pour que l’espace soit plus personnel.',
        missingCredentials: 'L’email et le mot de passe sont requis.',
        incorrectCredentials: 'L’email ou le mot de passe est incorrect.',
        duplicateEmail: 'Cet email possède déjà un compte Type1 and 2.',
        requestFailed: 'La requête a échoué. Réessayez.',
      },
    },
    signup: {
      eyebrow: 'Créer Un Compte',
      title: 'Créez votre compte Type1 and 2',
      subtitle: 'Créez votre compte Type1 and 2 pour le soutien familial quotidien.',
      primary: 'Créer L’Espace',
      back: 'Retour Au Site Public',
      switchLabel: 'Vous avez déjà un compte ?',
      switchAction: 'Se connecter',
      working: 'Traitement...',
      fields: {
        fullName: 'Nom Complet',
        role: 'Rôle',
        organization: 'Clinique / Organisation',
        email: 'Email',
        password: 'Mot De Passe',
      },
      placeholders: {
        fullName: 'Anne Martin',
        organization: 'Optionnel',
        email: 'you@example.com',
        password: 'Choisissez un mot de passe',
      },
      roles: {
        parent: 'Parent',
        adult: 'Adulte Vivant Avec Un Diabète',
        caregiver: 'Adulte De Soutien',
      },
      errors: {
        missingName: 'Ajoutez un nom pour que l’espace soit plus personnel.',
        missingCredentials: 'L’email et le mot de passe sont requis.',
        incorrectCredentials: 'L’email ou le mot de passe est incorrect.',
        duplicateEmail: 'Cet email possède déjà un compte Type1 and 2.',
        requestFailed: 'La requête a échoué. Réessayez.',
      },
    },
  },
  de: {
    signin: {
      eyebrow: 'Mitgliederzugang',
      title: 'Öffnen Sie Ihren Type1 and 2-Bereich',
      subtitle: 'Verwenden Sie Ihr Type1 and 2-Konto, um Ihren Unterstützungsbereich zu öffnen.',
      primary: 'Bereich Öffnen',
      back: 'Zurück Zur Öffentlichen Seite',
      switchLabel: 'Brauchen Sie ein neues Konto?',
      switchAction: 'Konto erstellen',
      working: 'Wird ausgeführt...',
      fields: {
        fullName: 'Vollständiger Name',
        role: 'Rolle',
        organization: 'Klinik / Organisation',
        email: 'Email',
        password: 'Passwort',
      },
      placeholders: {
        fullName: 'Anna Weber',
        organization: 'Optional',
        email: 'you@example.com',
        password: 'Passwort eingeben',
      },
      roles: {
        parent: 'Elternteil',
        adult: 'Erwachsene Person Mit Diabetes',
        caregiver: 'Betreuungsperson',
      },
      errors: {
        missingName: 'Bitte geben Sie einen Namen an, damit sich der Bereich persönlicher anfühlt.',
        missingCredentials: 'Email und Passwort sind erforderlich.',
        incorrectCredentials: 'Email oder Passwort sind falsch.',
        duplicateEmail: 'Diese Email hat bereits ein Type1 and 2-Konto.',
        requestFailed: 'Die Anfrage ist fehlgeschlagen. Bitte erneut versuchen.',
      },
    },
    signup: {
      eyebrow: 'Konto Erstellen',
      title: 'Erstellen Sie Ihr Type1 and 2-Konto',
      subtitle: 'Erstellen Sie Ihr Type1 and 2-Konto für die tägliche Familienunterstützung.',
      primary: 'Bereich Erstellen',
      back: 'Zurück Zur Öffentlichen Seite',
      switchLabel: 'Konto bereits erstellt?',
      switchAction: 'Anmelden',
      working: 'Wird ausgeführt...',
      fields: {
        fullName: 'Vollständiger Name',
        role: 'Rolle',
        organization: 'Klinik / Organisation',
        email: 'Email',
        password: 'Passwort',
      },
      placeholders: {
        fullName: 'Anna Weber',
        organization: 'Optional',
        email: 'you@example.com',
        password: 'Passwort wählen',
      },
      roles: {
        parent: 'Elternteil',
        adult: 'Erwachsene Person Mit Diabetes',
        caregiver: 'Betreuungsperson',
      },
      errors: {
        missingName: 'Bitte geben Sie einen Namen an, damit sich der Bereich persönlicher anfühlt.',
        missingCredentials: 'Email und Passwort sind erforderlich.',
        incorrectCredentials: 'Email oder Passwort sind falsch.',
        duplicateEmail: 'Diese Email hat bereits ein Type1 and 2-Konto.',
        requestFailed: 'Die Anfrage ist fehlgeschlagen. Bitte erneut versuchen.',
      },
    },
  },
  zh: {
    signin: {
      eyebrow: '成员访问',
      title: '打开你的 Type1 and 2 支持空间',
      subtitle: '使用你的 Type1 and 2 账户进入你的支持区域。',
      primary: '打开空间',
      back: '返回公开网站',
      switchLabel: '需要新账户？',
      switchAction: '创建账户',
      working: '处理中...',
      fields: {
        fullName: '全名',
        role: '角色',
        organization: '诊所 / 机构',
        email: '邮箱',
        password: '密码',
      },
      placeholders: {
        fullName: '安娜 王',
        organization: '可选',
        email: 'you@example.com',
        password: '输入你的密码',
      },
      roles: {
        parent: '家长',
        adult: '患有糖尿病的成年人',
        caregiver: '支持的大人',
      },
      errors: {
        missingName: '请填写姓名，这样这个空间会更有个人感。',
        missingCredentials: '邮箱和密码为必填项。',
        incorrectCredentials: '邮箱或密码不正确。',
        duplicateEmail: '此邮箱已经有一个 Type1 and 2 账户。',
        requestFailed: '请求失败。请再试一次。',
      },
    },
    signup: {
      eyebrow: '创建账户',
      title: '创建你的 Type1 and 2 账户',
      subtitle: '创建 Type1 and 2 账户，用于日常家庭支持。',
      primary: '创建空间',
      back: '返回公开网站',
      switchLabel: '已经有账户了？',
      switchAction: '登录',
      working: '处理中...',
      fields: {
        fullName: '全名',
        role: '角色',
        organization: '诊所 / 机构',
        email: '邮箱',
        password: '密码',
      },
      placeholders: {
        fullName: '安娜 王',
        organization: '可选',
        email: 'you@example.com',
        password: '设置密码',
      },
      roles: {
        parent: '家长',
        adult: '患有糖尿病的成年人',
        caregiver: '支持的大人',
      },
      errors: {
        missingName: '请填写姓名，这样这个空间会更有个人感。',
        missingCredentials: '邮箱和密码为必填项。',
        incorrectCredentials: '邮箱或密码不正确。',
        duplicateEmail: '此邮箱已经有一个 Type1 and 2 账户。',
        requestFailed: '请求失败。请再试一次。',
      },
    },
  },
  ja: {
    signin: {
      eyebrow: 'メンバーアクセス',
      title: 'Type1 and 2 の支援スペースを開く',
      subtitle: 'Type1 and 2 アカウントを使って支援エリアに入ります。',
      primary: 'スペースを開く',
      back: '公開サイトへ戻る',
      switchLabel: '新しいアカウントが必要ですか？',
      switchAction: 'アカウントを作成',
      working: '処理中...',
      fields: {
        fullName: '氏名',
        role: '役割',
        organization: 'クリニック / 組織',
        email: 'メール',
        password: 'パスワード',
      },
      placeholders: {
        fullName: 'Anna Sato',
        organization: '任意',
        email: 'you@example.com',
        password: 'パスワードを入力',
      },
      roles: {
        parent: '保護者',
        adult: '糖尿病のある成人',
        caregiver: '支える大人',
      },
      errors: {
        missingName: 'この空間を自分のものとして感じられるよう、名前を入力してください。',
        missingCredentials: 'メールとパスワードは必須です。',
        incorrectCredentials: 'メールまたはパスワードが正しくありません。',
        duplicateEmail: 'このメールにはすでに Type1 and 2 アカウントがあります。',
        requestFailed: 'リクエストに失敗しました。もう一度お試しください。',
      },
    },
    signup: {
      eyebrow: 'アカウント作成',
      title: 'Type1 and 2 アカウントを作成する',
      subtitle: '日常の家族サポートのために Type1 and 2 アカウントを作成します。',
      primary: 'スペースを作成',
      back: '公開サイトへ戻る',
      switchLabel: 'すでにアカウントがありますか？',
      switchAction: 'サインイン',
      working: '処理中...',
      fields: {
        fullName: '氏名',
        role: '役割',
        organization: 'クリニック / 組織',
        email: 'メール',
        password: 'パスワード',
      },
      placeholders: {
        fullName: 'Anna Sato',
        organization: '任意',
        email: 'you@example.com',
        password: 'パスワードを選択',
      },
      roles: {
        parent: '保護者',
        adult: '糖尿病のある成人',
        caregiver: '支える大人',
      },
      errors: {
        missingName: 'この空間を自分のものとして感じられるよう、名前を入力してください。',
        missingCredentials: 'メールとパスワードは必須です。',
        incorrectCredentials: 'メールまたはパスワードが正しくありません。',
        duplicateEmail: 'このメールにはすでに Type1 and 2 アカウントがあります。',
        requestFailed: 'リクエストに失敗しました。もう一度お試しください。',
      },
    },
  },
  pt: {
    signin: {
      eyebrow: 'Acesso De Membros',
      title: 'Abra seu espaço de apoio Type1 and 2',
      subtitle: 'Use sua conta Type1 and 2 para entrar na sua área de apoio.',
      primary: 'Abrir Espaço',
      back: 'Voltar Ao Site Público',
      switchLabel: 'Precisa de uma nova conta?',
      switchAction: 'Criar conta',
      working: 'Processando...',
      fields: {
        fullName: 'Nome Completo',
        role: 'Função',
        organization: 'Clínica / Organização',
        email: 'Email',
        password: 'Senha',
      },
      placeholders: {
        fullName: 'Ana Souza',
        organization: 'Opcional',
        email: 'you@example.com',
        password: 'Digite sua senha',
      },
      roles: {
        parent: 'Responsável',
        adult: 'Adulto Com Diabetes',
        caregiver: 'Adulto De Apoio',
      },
      errors: {
        missingName: 'Adicione um nome para que o espaço pareça pessoal.',
        missingCredentials: 'Email e senha são obrigatórios.',
        incorrectCredentials: 'Email ou senha incorretos.',
        duplicateEmail: 'Este email já possui uma conta Type1 and 2.',
        requestFailed: 'A solicitação falhou. Tente novamente.',
      },
    },
    signup: {
      eyebrow: 'Criar Conta',
      title: 'Crie sua conta Type1 and 2',
      subtitle: 'Crie sua conta Type1 and 2 para o apoio familiar diário.',
      primary: 'Criar Espaço',
      back: 'Voltar Ao Site Público',
      switchLabel: 'Já criou uma conta?',
      switchAction: 'Entrar',
      working: 'Processando...',
      fields: {
        fullName: 'Nome Completo',
        role: 'Função',
        organization: 'Clínica / Organização',
        email: 'Email',
        password: 'Senha',
      },
      placeholders: {
        fullName: 'Ana Souza',
        organization: 'Opcional',
        email: 'you@example.com',
        password: 'Escolha uma senha',
      },
      roles: {
        parent: 'Responsável',
        adult: 'Adulto Com Diabetes',
        caregiver: 'Adulto De Apoio',
      },
      errors: {
        missingName: 'Adicione um nome para que o espaço pareça pessoal.',
        missingCredentials: 'Email e senha são obrigatórios.',
        incorrectCredentials: 'Email ou senha incorretos.',
        duplicateEmail: 'Este email já possui uma conta Type1 and 2.',
        requestFailed: 'A solicitação falhou. Tente novamente.',
      },
    },
  },
  he: {
    signin: {
      eyebrow: 'גישת חברים',
      title: 'פתחו את מרחב התמיכה של Type1 and 2',
      subtitle: 'השתמשו בחשבון ה-Type1 and 2 שלכם כדי להיכנס לאזור התמיכה שלכם.',
      primary: 'פתח מרחב',
      back: 'חזרה לאתר הציבורי',
      switchLabel: 'צריך חשבון חדש?',
      switchAction: 'יצירת חשבון',
      working: 'מבצע...',
      fields: {
        fullName: 'שם מלא',
        role: 'תפקיד',
        organization: 'קליניקה / ארגון',
        email: 'אימייל',
        password: 'סיסמה',
      },
      placeholders: {
        fullName: 'אנה לוי',
        organization: 'אופציונלי',
        email: 'you@example.com',
        password: 'הכניסו את הסיסמה שלכם',
      },
      roles: {
        parent: 'הורה',
        adult: 'מבוגר שחי עם Type1 and 2',
        caregiver: 'מבוגר תומך',
      },
      errors: {
        missingName: 'אנא הוסיפו שם כדי שהמרחב ירגיש אישי.',
        missingCredentials: 'נדרשים אימייל וסיסמה.',
        incorrectCredentials: 'האימייל או הסיסמה שגויים.',
        duplicateEmail: 'לאימייל הזה כבר יש חשבון Type1 and 2.',
        requestFailed: 'הבקשה נכשלה. נסו שוב.',
      },
    },
    signup: {
      eyebrow: 'יצירת חשבון',
      title: 'צרו את חשבון ה-Type1 and 2 שלכם',
      subtitle: 'צרו חשבון Type1 and 2 לתמיכה משפחתית יומית.',
      primary: 'צור מרחב',
      back: 'חזרה לאתר הציבורי',
      switchLabel: 'כבר יצרתם חשבון?',
      switchAction: 'התחברות',
      working: 'מבצע...',
      fields: {
        fullName: 'שם מלא',
        role: 'תפקיד',
        organization: 'קליניקה / ארגון',
        email: 'אימייל',
        password: 'סיסמה',
      },
      placeholders: {
        fullName: 'אנה לוי',
        organization: 'אופציונלי',
        email: 'you@example.com',
        password: 'בחרו סיסמה',
      },
      roles: {
        parent: 'הורה',
        adult: 'מבוגר שחי עם Type1 and 2',
        caregiver: 'מבוגר תומך',
      },
      errors: {
        missingName: 'אנא הוסיפו שם כדי שהמרחב ירגיש אישי.',
        missingCredentials: 'נדרשים אימייל וסיסמה.',
        incorrectCredentials: 'האימייל או הסיסמה שגויים.',
        duplicateEmail: 'לאימייל הזה כבר יש חשבון Type1 and 2.',
        requestFailed: 'הבקשה נכשלה. נסו שוב.',
      },
    },
  },
  ar: {
    signin: {
      eyebrow: 'وصول الأعضاء',
      title: 'افتح مساحة الدعم الخاصة بك',
      subtitle: 'استخدم حساب Type1 and 2 الخاص بك للدخول إلى منطقة الدعم الخاصة بك.',
      primary: 'افتح المساحة',
      back: 'العودة إلى الموقع العام',
      switchLabel: 'هل تحتاج إلى حساب جديد؟',
      switchAction: 'إنشاء حساب',
      working: 'جار التنفيذ...',
      fields: {
        fullName: 'الاسم الكامل',
        role: 'الدور',
        organization: 'العيادة / المؤسسة',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
      },
      placeholders: {
        fullName: 'آنا علي',
        organization: 'اختياري',
        email: 'you@example.com',
        password: 'أدخل كلمة المرور',
      },
      roles: {
        parent: 'ولي أمر',
        adult: 'بالغ يعيش مع السكري',
        caregiver: 'شخص بالغ داعم',
      },
      errors: {
        missingName: 'يرجى إضافة اسم حتى تبدو مساحة العمل شخصية.',
        missingCredentials: 'البريد الإلكتروني وكلمة المرور مطلوبان.',
        incorrectCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحين.',
        duplicateEmail: 'هذا البريد الإلكتروني لديه بالفعل حساب Type1 and 2.',
        requestFailed: 'فشل الطلب. حاول مرة أخرى.',
      },
    },
    signup: {
      eyebrow: 'إنشاء حساب',
      title: 'أنشئ حساب Type1 and 2 الخاص بك',
      subtitle: 'أنشئ حساب Type1 and 2 لدعم الأسرة اليومي.',
      primary: 'أنشئ المساحة',
      back: 'العودة إلى الموقع العام',
      switchLabel: 'هل لديك حساب بالفعل؟',
      switchAction: 'تسجيل الدخول',
      working: 'جار التنفيذ...',
      fields: {
        fullName: 'الاسم الكامل',
        role: 'الدور',
        organization: 'العيادة / المؤسسة',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
      },
      placeholders: {
        fullName: 'آنا علي',
        organization: 'اختياري',
        email: 'you@example.com',
        password: 'اختر كلمة مرور',
      },
      roles: {
        parent: 'ولي أمر',
        adult: 'بالغ يعيش مع السكري',
        caregiver: 'شخص بالغ داعم',
      },
      errors: {
        missingName: 'يرجى إضافة اسم حتى تبدو مساحة العمل شخصية.',
        missingCredentials: 'البريد الإلكتروني وكلمة المرور مطلوبان.',
        incorrectCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحين.',
        duplicateEmail: 'هذا البريد الإلكتروني لديه بالفعل حساب Type1 and 2.',
        requestFailed: 'فشل الطلب. حاول مرة أخرى.',
      },
    },
  },
};

export const RESET_COPY: Record<Language, {
  forgot: string;
  sendLink: string;
  tokenPlaceholder: string;
  updatePassword: string;
  passwordUpdated: string;
  title: string;
  body: string;
  emailRequired: string;
  tokenRequired: string;
  backToSignIn: string;
  devTokenNote: string;
}> = {
  en: {
    forgot: 'Forgot password?',
    sendLink: 'Send reset link',
    tokenPlaceholder: 'Paste reset token from email',
    updatePassword: 'Update password',
    passwordUpdated: 'Password updated. Sign in again.',
    title: 'Reset your password',
    body: 'Enter your email and we will send a reset token. In development the token may appear here after you submit.',
    emailRequired: 'Enter your email first.',
    tokenRequired: 'Enter the reset token and a new password.',
    backToSignIn: 'Back to sign in',
    devTokenNote: 'Development token (copy if email is not configured):',
  },
  ru: {
    forgot: 'Забыли пароль?',
    sendLink: 'Отправить сброс',
    tokenPlaceholder: 'Вставьте токен из письма',
    updatePassword: 'Обновить пароль',
    passwordUpdated: 'Пароль обновлён. Войдите снова.',
    title: 'Сброс пароля',
    body: 'Введите email — мы отправим токен сброса. В режиме разработки токен может появиться здесь после отправки.',
    emailRequired: 'Сначала введите email.',
    tokenRequired: 'Введите токен сброса и новый пароль.',
    backToSignIn: 'Назад ко входу',
    devTokenNote: 'Токен для разработки (скопируйте, если почта не настроена):',
  },
  uk: {
    forgot: 'Забули пароль?',
    sendLink: 'Надіслати скидання',
    tokenPlaceholder: 'Вставте токен з листа',
    updatePassword: 'Оновити пароль',
    passwordUpdated: 'Пароль оновлено. Увійдіть знову.',
    title: 'Скидання пароля',
    body: 'Введіть email — надішлемо токен скидання. У режимі розробки токен може зʼявитися тут.',
    emailRequired: 'Спочатку введіть email.',
    tokenRequired: 'Введіть токен і новий пароль.',
    backToSignIn: 'Назад до входу',
    devTokenNote: 'Токен для розробки:',
  },
  es: {
    forgot: '¿Olvidaste tu contraseña?',
    sendLink: 'Enviar enlace de restablecimiento',
    tokenPlaceholder: 'Pega el token del correo',
    updatePassword: 'Actualizar contraseña',
    passwordUpdated: 'Contraseña actualizada. Inicia sesión de nuevo.',
    title: 'Restablecer contraseña',
    body: 'Introduce tu email y enviaremos un token. En desarrollo puede mostrarse aquí.',
    emailRequired: 'Introduce tu email primero.',
    tokenRequired: 'Introduce el token y una nueva contraseña.',
    backToSignIn: 'Volver a iniciar sesión',
    devTokenNote: 'Token de desarrollo:',
  },
  fr: {
    forgot: 'Mot de passe oublié ?',
    sendLink: 'Envoyer le lien de réinitialisation',
    tokenPlaceholder: 'Collez le jeton reçu par email',
    updatePassword: 'Mettre à jour le mot de passe',
    passwordUpdated: 'Mot de passe mis à jour. Reconnectez-vous.',
    title: 'Réinitialiser le mot de passe',
    body: 'Entrez votre email — nous enverrons un jeton. En développement, il peut s’afficher ici.',
    emailRequired: 'Entrez d’abord votre email.',
    tokenRequired: 'Entrez le jeton et un nouveau mot de passe.',
    backToSignIn: 'Retour à la connexion',
    devTokenNote: 'Jeton de développement :',
  },
  de: {
    forgot: 'Passwort vergessen?',
    sendLink: 'Reset-Link senden',
    tokenPlaceholder: 'Reset-Token aus E-Mail einfügen',
    updatePassword: 'Passwort aktualisieren',
    passwordUpdated: 'Passwort aktualisiert. Melden Sie sich erneut an.',
    title: 'Passwort zurücksetzen',
    body: 'E-Mail eingeben — wir senden einen Token. In der Entwicklung kann er hier erscheinen.',
    emailRequired: 'Bitte zuerst E-Mail eingeben.',
    tokenRequired: 'Token und neues Passwort eingeben.',
    backToSignIn: 'Zurück zur Anmeldung',
    devTokenNote: 'Entwicklungs-Token:',
  },
  zh: {
    forgot: '忘记密码？',
    sendLink: '发送重置链接',
    tokenPlaceholder: '粘贴邮件中的重置令牌',
    updatePassword: '更新密码',
    passwordUpdated: '密码已更新，请重新登录。',
    title: '重置密码',
    body: '输入邮箱，我们将发送重置令牌。开发模式下令牌可能显示在此处。',
    emailRequired: '请先输入邮箱。',
    tokenRequired: '请输入令牌和新密码。',
    backToSignIn: '返回登录',
    devTokenNote: '开发令牌：',
  },
  ja: {
    forgot: 'パスワードをお忘れですか？',
    sendLink: 'リセットリンクを送信',
    tokenPlaceholder: 'メールのリセットトークンを貼り付け',
    updatePassword: 'パスワードを更新',
    passwordUpdated: 'パスワードを更新しました。再度サインインしてください。',
    title: 'パスワードをリセット',
    body: 'メールアドレスを入力するとリセットトークンを送ります。開発中はここに表示される場合があります。',
    emailRequired: '先にメールアドレスを入力してください。',
    tokenRequired: 'トークンと新しいパスワードを入力してください。',
    backToSignIn: 'サインインに戻る',
    devTokenNote: '開発用トークン：',
  },
  pt: {
    forgot: 'Esqueceu a senha?',
    sendLink: 'Enviar link de redefinição',
    tokenPlaceholder: 'Cole o token do email',
    updatePassword: 'Atualizar senha',
    passwordUpdated: 'Senha atualizada. Entre novamente.',
    title: 'Redefinir senha',
    body: 'Digite seu email — enviaremos um token. Em desenvolvimento, ele pode aparecer aqui.',
    emailRequired: 'Digite seu email primeiro.',
    tokenRequired: 'Digite o token e uma nova senha.',
    backToSignIn: 'Voltar ao login',
    devTokenNote: 'Token de desenvolvimento:',
  },
  he: {
    forgot: 'שכחתם סיסמה?',
    sendLink: 'שלח קישור לאיפוס',
    tokenPlaceholder: 'הדביקו את האסימון מהמייל',
    updatePassword: 'עדכן סיסמה',
    passwordUpdated: 'הסיסמה עודכנה. התחברו שוב.',
    title: 'איפוס סיסמה',
    body: 'הזינו אימייל — נשלח אסימון איפוס. בפיתוח האסימון עשוי להופיע כאן.',
    emailRequired: 'הזינו אימייל קודם.',
    tokenRequired: 'הזינו אסימון וסיסמה חדשה.',
    backToSignIn: 'חזרה להתחברות',
    devTokenNote: 'אסימון פיתוח:',
  },
  ar: {
    forgot: 'هل نسيت كلمة المرور؟',
    sendLink: 'إرسال رابط إعادة التعيين',
    tokenPlaceholder: 'الصق رمز إعادة التعيين من البريد',
    updatePassword: 'تحديث كلمة المرور',
    passwordUpdated: 'تم تحديث كلمة المرور. سجّل الدخول مرة أخرى.',
    title: 'إعادة تعيين كلمة المرور',
    body: 'أدخل بريدك — سنرسل رمز إعادة التعيين. في وضع التطوير قد يظهر هنا.',
    emailRequired: 'أدخل البريد أولاً.',
    tokenRequired: 'أدخل الرمز وكلمة مرور جديدة.',
    backToSignIn: 'العودة لتسجيل الدخول',
    devTokenNote: 'رمز التطوير:',
  },
};

export const AUTH_TYPE_COPY: Record<Language, {
  label: string;
  hint: string;
  choiceRequired: string;
  type1: { badge: string; title: string; body: string };
  type2: { badge: string; title: string; body: string };
  both: { badge: string; title: string; body: string };
}> = {
  en: {
    label: 'How do you want to join?',
    hint: 'Type 1 and Type 2 use different day defaults, alerts, and family roles. Choose one path now — or pick the exact type during setup.',
    choiceRequired: 'Choose Join Type 1, Join Type 2, or Join Type 1 and 2.',
    type1: { badge: 'TYPE 1', title: 'Join Type 1', body: 'Insulin-dependent households. Stronger low alerts, parent/caregiver roles, night escalation.' },
    type2: { badge: 'TYPE 2', title: 'Join Type 2', body: 'Gentler day rhythm, earlier high-glucose attention, adult-led household defaults.' },
    both: { badge: 'TYPE 1 & 2', title: 'Join Type 1 and 2', body: 'For families that need both paths. You will choose the exact type in household setup.' },
  },
  ru: {
    label: 'Как вы хотите присоединиться?',
    hint: 'Тип 1 и тип 2 — разные дневные настройки, сигналы и роли. Выберите путь сейчас или уточните тип при настройке семьи.',
    choiceRequired: 'Выберите: Join Type 1, Join Type 2 или Join Type 1 and 2.',
    type1: { badge: 'ТИП 1', title: 'Join Type 1', body: 'Семьи с СД 1 типа. Сильнее сигналы при низком сахаре, роли родителя и опекуна, ночная эскалация.' },
    type2: { badge: 'ТИП 2', title: 'Join Type 2', body: 'Мягче дневной ритм, раньше внимание к высокому сахару, настройки для взрослого в семье.' },
    both: { badge: 'ТИП 1 И 2', title: 'Join Type 1 and 2', body: 'Если нужны оба пути. Точный тип вы выберете при настройке семьи.' },
  },
  uk: {
    label: 'Як ви хочете приєднатися?',
    hint: 'Тип 1 і тип 2 мають різні денні налаштування, сигнали та ролі. Оберіть шлях зараз або уточніть тип під час налаштування.',
    choiceRequired: 'Оберіть Join Type 1, Join Type 2 або Join Type 1 and 2.',
    type1: { badge: 'ТИП 1', title: 'Join Type 1', body: 'Сімʼї з ЦД 1 типу. Сильніші сигнали при низькому цукрі, ролі батьків, нічна ескалація.' },
    type2: { badge: 'ТИП 2', title: 'Join Type 2', body: 'Мʼякший денний ритм, раніше увага до високого цукру, налаштування для дорослого.' },
    both: { badge: 'ТИП 1 І 2', title: 'Join Type 1 and 2', body: 'Якщо потрібні обидва шляхи. Точний тип оберете під час налаштування сімʼї.' },
  },
  es: {
    label: '¿Cómo quieres unirte?',
    hint: 'Tipo 1 y tipo 2 usan alertas, roles y ritmos distintos. Elige un camino ahora o el tipo exacto en la configuración.',
    choiceRequired: 'Elige Join Type 1, Join Type 2 o Join Type 1 and 2.',
    type1: { badge: 'TIPO 1', title: 'Join Type 1', body: 'Hogares con diabetes tipo 1. Alertas más fuertes por bajas, roles de padres/cuidadores, escalada nocturna.' },
    type2: { badge: 'TIPO 2', title: 'Join Type 2', body: 'Ritmo diurno más suave, atención temprana a glucosa alta, hogar orientado al adulto.' },
    both: { badge: 'TIPO 1 Y 2', title: 'Join Type 1 and 2', body: 'Para familias que necesitan ambos caminos. El tipo exacto se elige en la configuración del hogar.' },
  },
  fr: {
    label: 'Comment souhaitez-vous rejoindre ?',
    hint: 'Type 1 et type 2 ont des alertes, rôles et rythmes différents. Choisissez un chemin maintenant ou le type exact lors de la configuration.',
    choiceRequired: 'Choisissez Join Type 1, Join Type 2 ou Join Type 1 and 2.',
    type1: { badge: 'TYPE 1', title: 'Join Type 1', body: 'Foyers type 1. Alertes basses plus fortes, rôles parents/aidants, escalade nocturne.' },
    type2: { badge: 'TYPE 2', title: 'Join Type 2', body: 'Rythme diurne plus doux, attention précoce aux hyperglycémies, foyer centré sur l’adulte.' },
    both: { badge: 'TYPE 1 ET 2', title: 'Join Type 1 and 2', body: 'Pour les familles qui ont besoin des deux chemins. Le type exact se choisit lors de la configuration.' },
  },
  de: {
    label: 'Wie möchten Sie beitreten?',
    hint: 'Typ 1 und Typ 2 haben unterschiedliche Tagesdefaults, Warnungen und Rollen. Wählen Sie jetzt einen Weg oder den genauen Typ im Setup.',
    choiceRequired: 'Wählen Sie Join Type 1, Join Type 2 oder Join Type 1 and 2.',
    type1: { badge: 'TYP 1', title: 'Join Type 1', body: 'Haushalte mit Typ 1. Stärkere Unterzucker-Warnungen, Eltern-/Betreuerrollen, Nacht-Eskalation.' },
    type2: { badge: 'TYP 2', title: 'Join Type 2', body: 'Sanfterer Tagesrhythmus, frühere Aufmerksamkeit bei hohen Werten, erwachsenenzentriertes Setup.' },
    both: { badge: 'TYP 1 & 2', title: 'Join Type 1 and 2', body: 'Für Familien, die beide Wege brauchen. Den genauen Typ wählen Sie in der Haushaltseinrichtung.' },
  },
  zh: {
    label: '您想如何加入？',
    hint: '1 型和 2 型使用不同的日间默认、提醒和家庭角色。现在选择路径，或在设置中确定具体类型。',
    choiceRequired: '请选择 Join Type 1、Join Type 2 或 Join Type 1 and 2。',
    type1: { badge: '1 型', title: 'Join Type 1', body: '1 型家庭。低血糖提醒更强，家长/照护角色，夜间升级。' },
    type2: { badge: '2 型', title: 'Join Type 2', body: '更温和的日间节奏，更早关注高血糖，以成人为主的家庭默认。' },
    both: { badge: '1 型 & 2 型', title: 'Join Type 1 and 2', body: '需要两条路径的家庭。具体类型在家庭设置中选择。' },
  },
  ja: {
    label: 'どの方法で参加しますか？',
    hint: '1型と2型では日中の既定値、アラート、家族の役割が異なります。今選ぶか、設定で正確なタイプを選べます。',
    choiceRequired: 'Join Type 1、Join Type 2、Join Type 1 and 2 のいずれかを選んでください。',
    type1: { badge: '1型', title: 'Join Type 1', body: '1型の家庭向け。低値アラートが強め、保護者・支援役、夜間エスカレーション。' },
    type2: { badge: '2型', title: 'Join Type 2', body: '日中は穏やか、高値への注意が早い、成人中心の家庭設定。' },
    both: { badge: '1型 & 2型', title: 'Join Type 1 and 2', body: '両方の経路が必要な家庭向け。正確なタイプは家庭設定で選びます。' },
  },
  pt: {
    label: 'Como você quer entrar?',
    hint: 'Tipo 1 e tipo 2 usam alertas, papéis e ritmos diferentes. Escolha um caminho agora ou o tipo exato na configuração.',
    choiceRequired: 'Escolha Join Type 1, Join Type 2 ou Join Type 1 and 2.',
    type1: { badge: 'TIPO 1', title: 'Join Type 1', body: 'Famílias tipo 1. Alertas de baixa mais fortes, papéis de pais/cuidadores, escalada noturna.' },
    type2: { badge: 'TIPO 2', title: 'Join Type 2', body: 'Ritmo diurno mais suave, atenção precoce a glicose alta, padrões centrados no adulto.' },
    both: { badge: 'TIPO 1 E 2', title: 'Join Type 1 and 2', body: 'Para famílias que precisam dos dois caminhos. O tipo exato é escolhido na configuração da família.' },
  },
  he: {
    label: 'איך תרצו להצטרף?',
    hint: 'סוג 1 וסוג 2 משתמשים בהגדרות יום, התראות ותפקידים שונים. בחרו נתיב עכשיו או את הסוג המדויק בהגדרת המשפחה.',
    choiceRequired: 'בחרו Join Type 1, Join Type 2 או Join Type 1 and 2.',
    type1: { badge: 'סוג 1', title: 'Join Type 1', body: 'משפחות סוג 1. התראות נמוכות חזקות יותר, תפקידי הורה/תומך, הסלמה לילית.' },
    type2: { badge: 'סוג 2', title: 'Join Type 2', body: 'קצב יום רך יותר, תשומת לב מוקדמת לערכים גבוהים, ברירות מחדל למבוגר.' },
    both: { badge: 'סוג 1 ו-2', title: 'Join Type 1 and 2', body: 'למשפחות שצריכות את שני הנתיבים. הסוג המדויק נבחר בהגדרת המשפחה.' },
  },
  ar: {
    label: 'كيف تريد الانضمام؟',
    hint: 'النوع 1 والنوع 2 يستخدمان إعدادات يوم وتنبيهات وأدوارًا مختلفة. اختر مسارًا الآن أو النوع الدقيق في إعداد الأسرة.',
    choiceRequired: 'اختر Join Type 1 أو Join Type 2 أو Join Type 1 and 2.',
    type1: { badge: 'النوع 1', title: 'Join Type 1', body: 'أسر النوع 1. تنبيهات أقوى للانخفاض، أدوار الوالدين/الداعم، تصعيد ليلي.' },
    type2: { badge: 'النوع 2', title: 'Join Type 2', body: 'إيقاع نهاري أخف، انتباه مبكر للارتفاع، إعدادات منزلية للبالغ.' },
    both: { badge: 'النوع 1 و 2', title: 'Join Type 1 and 2', body: 'للأسر التي تحتاج كلا المسارين. النوع الدقيق يُختار في إعداد الأسرة.' },
  },
};

export const AUTH_SOCIAL_COPY: Record<Language, {
  google: string;
  orEmail: string;
  showPassword: string;
  hidePassword: string;
  googleUnavailable: string;
  googleFailed: string;
  googleNoAccount: string;
  brandName: string;
}> = {
  en: { google: 'Continue with Google', orEmail: 'Or continue with email', showPassword: 'Show password', hidePassword: 'Hide password', googleUnavailable: 'Google sign-in is not configured yet.', googleFailed: 'Google sign-in failed. Try again or use email.', googleNoAccount: 'No Type1 and 2 account found for this Google email. Create one first.', brandName: 'Type1 and 2' },
  ru: { google: 'Продолжить через Google', orEmail: 'Или продолжить по email', showPassword: 'Показать пароль', hidePassword: 'Скрыть пароль', googleUnavailable: 'Вход через Google пока не настроен.', googleFailed: 'Не удалось войти через Google. Попробуйте снова или используйте email.', googleNoAccount: 'Аккаунт Type1 and 2 для этого Google email не найден. Сначала создайте его.', brandName: 'Type1 and 2' },
  uk: { google: 'Продовжити через Google', orEmail: 'Або продовжити через email', showPassword: 'Показати пароль', hidePassword: 'Приховати пароль', googleUnavailable: 'Вхід через Google ще не налаштовано.', googleFailed: 'Не вдалося увійти через Google. Спробуйте знову або використайте email.', googleNoAccount: 'Обліковий запис Type1 and 2 для цього Google email не знайдено. Спочатку створіть його.', brandName: 'Type1 and 2' },
  es: { google: 'Continuar con Google', orEmail: 'O continuar con email', showPassword: 'Mostrar contraseña', hidePassword: 'Ocultar contraseña', googleUnavailable: 'El inicio con Google aún no está configurado.', googleFailed: 'No se pudo iniciar sesión con Google. Inténtalo de nuevo o usa email.', googleNoAccount: 'No se encontró una cuenta Type1 and 2 para este email de Google. Créala primero.', brandName: 'Type1 and 2' },
  fr: { google: 'Continuer avec Google', orEmail: 'Ou continuer avec email', showPassword: 'Afficher le mot de passe', hidePassword: 'Masquer le mot de passe', googleUnavailable: 'La connexion Google n’est pas encore configurée.', googleFailed: 'Échec de la connexion Google. Réessayez ou utilisez l’email.', googleNoAccount: 'Aucun compte Type1 and 2 trouvé pour cet email Google. Créez-en un d’abord.', brandName: 'Type1 and 2' },
  de: { google: 'Mit Google fortfahren', orEmail: 'Oder mit E-Mail fortfahren', showPassword: 'Passwort anzeigen', hidePassword: 'Passwort verbergen', googleUnavailable: 'Google-Anmeldung ist noch nicht konfiguriert.', googleFailed: 'Google-Anmeldung fehlgeschlagen. Versuchen Sie es erneut oder nutzen Sie E-Mail.', googleNoAccount: 'Kein Type1 and 2-Konto für diese Google-E-Mail gefunden. Erstellen Sie zuerst eines.', brandName: 'Type1 and 2' },
  zh: { google: '使用 Google 继续', orEmail: '或使用邮箱继续', showPassword: '显示密码', hidePassword: '隐藏密码', googleUnavailable: 'Google 登录尚未配置。', googleFailed: 'Google 登录失败。请重试或使用邮箱。', googleNoAccount: '未找到此 Google 邮箱对应的 Type1 and 2 账户。请先创建账户。', brandName: 'Type1 and 2' },
  ja: { google: 'Google で続行', orEmail: 'またはメールで続行', showPassword: 'パスワードを表示', hidePassword: 'パスワードを非表示', googleUnavailable: 'Google サインインはまだ設定されていません。', googleFailed: 'Google サインインに失敗しました。再試行するかメールを使ってください。', googleNoAccount: 'この Google メールの Type1 and 2 アカウントが見つかりません。先に作成してください。', brandName: 'Type1 and 2' },
  pt: { google: 'Continuar com Google', orEmail: 'Ou continuar com email', showPassword: 'Mostrar senha', hidePassword: 'Ocultar senha', googleUnavailable: 'O login com Google ainda não está configurado.', googleFailed: 'Falha ao entrar com Google. Tente novamente ou use email.', googleNoAccount: 'Nenhuma conta Type1 and 2 encontrada para este email do Google. Crie uma primeiro.', brandName: 'Type1 and 2' },
  he: { google: 'המשיכו עם Google', orEmail: 'או המשיכו עם אימייל', showPassword: 'הצג סיסמה', hidePassword: 'הסתר סיסמה', googleUnavailable: 'כניסה עם Google עדיין לא מוגדרת.', googleFailed: 'הכניסה עם Google נכשלה. נסו שוב או השתמשו באימייל.', googleNoAccount: 'לא נמצא חשבון Type1 and 2 לכתובת Google הזו. צרו חשבון קודם.', brandName: 'Type1 and 2' },
  ar: { google: 'المتابعة مع Google', orEmail: 'أو المتابعة بالبريد الإلكتروني', showPassword: 'إظهار كلمة المرور', hidePassword: 'إخفاء كلمة المرور', googleUnavailable: 'تسجيل الدخول عبر Google غير مهيأ بعد.', googleFailed: 'فشل تسجيل الدخول عبر Google. حاول مرة أخرى أو استخدم البريد.', googleNoAccount: 'لم يتم العثور على حساب Type1 and 2 لهذا البريد في Google. أنشئ حسابًا أولًا.', brandName: 'Type1 and 2' },
};


