import type { Language } from '../types';

const localized = <T,>(value: Record<Language, T>) => value;

export const KNOWLEDGE_LABELS = {
  footer: localized({
    en: { how: 'How It Works', faq: 'FAQ', learn: 'Learning Center', news: 'Diabetes News', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    ru: { how: 'Как Это Работает', faq: 'FAQ', learn: 'Обучающий Центр', news: 'Новости Диабета', voiceGuide: 'Голосовой помощник', pricing: 'Тарифы' },
    uk: { how: 'Як Це Працює', faq: 'FAQ', learn: 'Навчальний Центр', news: 'Новини Діабету', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    es: { how: 'Cómo Funciona', faq: 'FAQ', learn: 'Centro De Aprendizaje', news: 'Noticias Sobre Diabetes', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    fr: { how: 'Comment Cela Marche', faq: 'FAQ', learn: 'Centre D’apprentissage', news: 'Actualités Du Diabète', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    de: { how: 'So Funktioniert Es', faq: 'FAQ', learn: 'Lernzentrum', news: 'Diabetes-Nachrichten', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    zh: { how: '工作方式', faq: '常见问题', learn: '学习中心', news: '糖尿病新闻', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    ja: { how: 'しくみ', faq: 'よくある質問', learn: '学習センター', news: '糖尿病ニュース', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    pt: { how: 'Como Funciona', faq: 'FAQ', learn: 'Centro De Aprendizado', news: 'Notícias Sobre Diabetes', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    he: { how: 'איך זה עובד', faq: 'שאלות נפוצות', learn: 'מרכז למידה', news: 'חדשות סוכרת', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
    ar: { how: 'كيف يعمل', faq: 'الأسئلة الشائعة', learn: 'مركز التعلّم', news: 'أخبار السكري', voiceGuide: 'Voice Guide', pricing: 'Pricing' },
  }),
  pages: localized({
    en: {
      howTitle: 'How T1D Works For Families',
      faqTitle: 'Frequently Asked Questions',
      learnTitle: 'Learning Center',
      newsTitle: 'Diabetes News',
      search: 'Search the learning library',
      searchNews: 'Search news topics',
      all: 'All',
      glossary: 'Glossary',
      library: 'Library',
      pathways: 'Core Topics',
      explore: 'Explore',
      updated: 'Latest Focus',
      accordionHint: 'Open a question to read the answer.',
      newsNote: 'News is structured for frequent updates and can be connected to a live source layer next.',
      articleHint: 'Open any topic to go deeper.',
    },
    ru: {
      howTitle: 'Как Система Помогает Семье',
      faqTitle: 'Частые Вопросы',
      learnTitle: 'Обучающий Центр',
      newsTitle: 'Новости Диабета',
      search: 'Поиск по библиотеке материалов',
      searchNews: 'Поиск по темам новостей',
      all: 'Все',
      glossary: 'Термины',
      library: 'Библиотека',
      pathways: 'Основные Темы',
      explore: 'Изучить',
      updated: 'Актуальный Фокус',
      accordionHint: 'Открой вопрос, чтобы увидеть ответ.',
      newsNote: 'Раздел новостей уже подготовлен для частых обновлений и может быть подключён к живому источнику.',
      articleHint: 'Открой тему, чтобы посмотреть подробнее.',
    },
    uk: {
      howTitle: 'Як Система Допомагає Родині',
      faqTitle: 'Поширені Запитання',
      learnTitle: 'Навчальний Центр',
      newsTitle: 'Новини Діабету',
      search: 'Пошук у бібліотеці матеріалів',
      searchNews: 'Пошук за темами новин',
      all: 'Усе',
      glossary: 'Терміни',
      library: 'Бібліотека',
      pathways: 'Основні Теми',
      explore: 'Дослідити',
      updated: 'Актуальний Фокус',
      accordionHint: 'Відкрийте запитання, щоб прочитати відповідь.',
      newsNote: 'Розділ новин уже підготовлений до частих оновлень і може бути підключений до живого джерела.',
      articleHint: 'Відкрийте тему, щоб зануритися глибше.',
    },
    es: {
      howTitle: 'Cómo Ayuda El Sistema A Las Familias',
      faqTitle: 'Preguntas Frecuentes',
      learnTitle: 'Centro De Aprendizaje',
      newsTitle: 'Noticias Sobre Diabetes',
      search: 'Buscar en la biblioteca de aprendizaje',
      searchNews: 'Buscar temas de noticias',
      all: 'Todo',
      glossary: 'Glosario',
      library: 'Biblioteca',
      pathways: 'Temas Clave',
      explore: 'Explorar',
      updated: 'Enfoque Actual',
      accordionHint: 'Abre una pregunta para leer la respuesta.',
      newsNote: 'La página de noticias ya está preparada para actualizaciones frecuentes y puede conectarse después a una fuente en vivo.',
      articleHint: 'Abre cualquier tema para profundizar.',
    },
    fr: {
      howTitle: 'Comment Le Système Aide Les Familles',
      faqTitle: 'Questions Fréquentes',
      learnTitle: 'Centre D’apprentissage',
      newsTitle: 'Actualités Du Diabète',
      search: 'Rechercher dans la bibliothèque',
      searchNews: 'Rechercher des sujets d’actualité',
      all: 'Tout',
      glossary: 'Glossaire',
      library: 'Bibliothèque',
      pathways: 'Thèmes Clés',
      explore: 'Explorer',
      updated: 'Point D’attention',
      accordionHint: 'Ouvrez une question pour lire la réponse.',
      newsNote: 'La page d’actualités est prête pour des mises à jour fréquentes et peut ensuite être reliée à une source en direct.',
      articleHint: 'Ouvrez un sujet pour aller plus loin.',
    },
    de: {
      howTitle: 'Wie Das System Familien Hilft',
      faqTitle: 'Häufige Fragen',
      learnTitle: 'Lernzentrum',
      newsTitle: 'Diabetes-Nachrichten',
      search: 'Lernbibliothek durchsuchen',
      searchNews: 'Nachrichtenthemen durchsuchen',
      all: 'Alle',
      glossary: 'Glossar',
      library: 'Bibliothek',
      pathways: 'Kernthemen',
      explore: 'Entdecken',
      updated: 'Aktueller Fokus',
      accordionHint: 'Öffnen Sie eine Frage, um die Antwort zu lesen.',
      newsNote: 'Die Nachrichtenseite ist bereits für häufige Updates vorbereitet und kann später an eine Live-Quelle angebunden werden.',
      articleHint: 'Öffnen Sie ein Thema, um tiefer einzusteigen.',
    },
    zh: {
      howTitle: '系统如何帮助家庭',
      faqTitle: '常见问题',
      learnTitle: '学习中心',
      newsTitle: '糖尿病新闻',
      search: '搜索学习资料库',
      searchNews: '搜索新闻主题',
      all: '全部',
      glossary: '术语表',
      library: '资料库',
      pathways: '核心主题',
      explore: '查看',
      updated: '当前重点',
      accordionHint: '打开问题即可查看答案。',
      newsNote: '新闻页面已经为频繁更新做好准备，之后可以接入实时来源。',
      articleHint: '打开任意主题即可了解更多。',
    },
    ja: {
      howTitle: '家族のためにどう役立つか',
      faqTitle: 'よくある質問',
      learnTitle: '学習センター',
      newsTitle: '糖尿病ニュース',
      search: '学習ライブラリを検索',
      searchNews: 'ニュースのテーマを検索',
      all: 'すべて',
      glossary: '用語集',
      library: 'ライブラリ',
      pathways: '主要テーマ',
      explore: '見る',
      updated: '現在の焦点',
      accordionHint: '質問を開くと回答が読めます。',
      newsNote: 'ニュースページは頻繁な更新に対応できる構成で、次にライブソースへ接続できます。',
      articleHint: 'テーマを開くと詳しく読めます。',
    },
    pt: {
      howTitle: 'Como O Sistema Ajuda As Famílias',
      faqTitle: 'Perguntas Frequentes',
      learnTitle: 'Centro De Aprendizado',
      newsTitle: 'Notícias Sobre Diabetes',
      search: 'Buscar na biblioteca de aprendizado',
      searchNews: 'Buscar temas de notícias',
      all: 'Tudo',
      glossary: 'Glossário',
      library: 'Biblioteca',
      pathways: 'Temas Centrais',
      explore: 'Explorar',
      updated: 'Foco Atual',
      accordionHint: 'Abra uma pergunta para ler a resposta.',
      newsNote: 'A página de notícias já está pronta para atualizações frequentes e pode ser conectada depois a uma fonte ao vivo.',
      articleHint: 'Abra qualquer tema para aprofundar.',
    },
    he: {
      howTitle: 'איך המערכת עוזרת למשפחות',
      faqTitle: 'שאלות נפוצות',
      learnTitle: 'מרכז למידה',
      newsTitle: 'חדשות סוכרת',
      search: 'חיפוש בספריית הלמידה',
      searchNews: 'חיפוש נושאי חדשות',
      all: 'הכול',
      glossary: 'מילון מונחים',
      library: 'ספרייה',
      pathways: 'נושאי ליבה',
      explore: 'לחקור',
      updated: 'מוקד נוכחי',
      accordionHint: 'פתחו שאלה כדי לקרוא את התשובה.',
      newsNote: 'עמוד החדשות כבר בנוי לעדכונים תכופים ויכול להתחבר בהמשך למקור חי.',
      articleHint: 'פתחו נושא כדי להעמיק.',
    },
    ar: {
      howTitle: 'كيف يساعد النظام العائلات',
      faqTitle: 'الأسئلة الشائعة',
      learnTitle: 'مركز التعلّم',
      newsTitle: 'أخبار السكري',
      search: 'ابحث في مكتبة التعلّم',
      searchNews: 'ابحث في موضوعات الأخبار',
      all: 'الكل',
      glossary: 'قاموس المصطلحات',
      library: 'المكتبة',
      pathways: 'الموضوعات الأساسية',
      explore: 'استكشف',
      updated: 'التركيز الحالي',
      accordionHint: 'افتح السؤال لقراءة الإجابة.',
      newsNote: 'صفحة الأخبار مهيأة للتحديثات المتكررة ويمكن ربطها لاحقاً بمصدر مباشر.',
      articleHint: 'افتح أي موضوع للتعمق أكثر.',
    },
  }),
};

